### PR TITLE
fix(jira): add incremental to worklog

### LINKED ISSUE #1677: Jira worklog collector lack update operation
## Describe the bug
Jira worklog collector can only work for getting all worklogs every time

## Expected behavior
This should also work for incremental update

### PR DESCRIPTION
**Pull request by warren830**
# Summary

add incremental update operation to jira worklog collector

### Key Points

- [ ] This is a breaking change
- [ ] New or existing documentation is updated

### Description
Describe what this PR does, and aims to solve in a few sentences.

### Does this close any open issues?
close #1677

### Current Behavior
Describe the current behaviour of this issue, if relevant.

### New Behavior
Describe the new behaviour updated in this issue, if relevant.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: plugins/jira/tasks/worklog_collector.go [hunk 1]
```diff
@@ -14,12 +15,34 @@ import (
...
+	}
+
 	logger := taskCtx.GetLogger()
-	db := taskCtx.GetDb()
 	sourceId := data.Source.ID
 	boardId := data.Options.BoardId
-	cursor, err := db.Model(&models.JiraBoardIssue{}).Select("issue_id, NOW() AS update_time").Where("source_id = ? AND board_id = ?", sourceId, boardId).Rows()
+	tx := db.Model(&models.JiraIssue{}).
+		Joins("left join _tool_jira_board_issues on _tool_jira_issues.issue_id = _tool_jira_board_issues.issue_id").
+		Select("_tool_jira_board_issues.issue_id, NOW() AS update_time").Where("_tool_jira_board_issues.source_id = ? AND _tool_jira_board_issues.board_id = ?", sourceId, boardId)
```
Comment (klesh) [inline plugins/jira/tasks/worklog_collector.go:40]: seems like we dont need the `apiv2models.Input.Updateime` at all ?

Comment (warren830) [reply plugins/jira/tasks/worklog_collector.go:40]: Yes, we don't need it, I will delete it

**Review by klesh — APPROVED** [review]
LGTM
