### PR TITLE
fix(api_collector): fix dead lock

### LINKED ISSUE #1693: api_collector dead lock
## Describe the bug
When we are running two plugins at the same time, one of them might get block.
This is caused by dead lock. We call scheduler.submit inside scheduler.submit in api_async_client.DoAsync

## Expected behavior
System should report error or continue working

### PR DESCRIPTION
**Pull request by warren830**
close #1693

# Summary

Add a subpool for scheduler to hold retry requests
And to avoid rate limit, for main pool submit, we will sleep for a second if there are still some running goroutines in the subpool. 

### Key Points

- [ ] This is a breaking change
- [ ] New or existing documentation is updated

### Description
Describe what this PR does, and aims to solve in a few sentences.

### Does this close any open issues?
close #1693 

### Current Behavior
Describe the current behaviour of this issue, if relevant.

### New Behavior
Describe the new behaviour updated in this issue, if relevant.

### Screenshots
image

image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: plugins/helper/api_async_client.go [hunk 1]
```diff
@@ -111,7 +112,8 @@ func (apiClient *ApiAsyncClient) DoAsync(
 		if err != nil {
 			if retry < apiClient.maxRetry && err != context.Canceled {
 				apiClient.logError("retry #%d for %s", retry, err.Error())
-				return apiClient.DoAsync(method, path, query, body, header, handler, retry+1)
+				retry++
+				return apiClient.scheduler.Submit(subFunc, apiClient.scheduler.subPool)
```
Comment (liangjingyang) [inline plugins/helper/api_async_client.go:116]: What if mainPool.workerNum * maxRetry > subPool.workerNum? Will the worker of subPool run out?

Comment (klesh) [reply plugins/helper/api_async_client.go:116]: I agree with @liangjingyang , this is effectively increasing the size of the pool, which can reduce the probability of dead locking, but not solving the root cause.

I think a better way to solve this is to use the same way to #1399

Comment (warren830) [reply plugins/helper/api_async_client.go:116]: I set the subpool's size to four times of mainpool. So it will not run out of workers

Comment (warren830) [reply plugins/helper/api_async_client.go:116]: Maybe I should set subpool's size to maxtry * size of mainpool

File: plugins/helper/worker_scheduler.go [hunk 2]
```diff
@@ -34,6 +35,12 @@ func NewWorkerScheduler(workerNum int, maxWork int, maxWorkDuration time.Duratio
 		workerErrors = append(*pWorkerErrors, i.(error))
 		pWorkerErrors = &workerErrors
 	}))
+	subPool, err := ants.NewPool(workerNum*5, ants.WithPanicHandler(func(i interface{}) {
+		mux.Lock()
```
Comment (warren830) [inline plugins/helper/worker_scheduler.go:39]: we can set the first param of newPool to workerNum * maxtry

File: plugins/helper/worker_scheduler.go [hunk 3]
```diff
@@ -78,6 +92,11 @@ func (s *WorkerScheduler) Submit(task func() error) error {
 				panic(fmt.Errorf("%s\n%s", err, cf))
 			}
 		}()
+		if pool == nil {
+			for s.subPool.Running() != 0 {
+				time.Sleep(1 * time.Second)
+			}
+		}
```
Comment (warren830) [inline plugins/helper/worker_scheduler.go:99]: Here, if there are still running workers in subpool, we can set a ticker here

File: plugins/helper/worker_scheduler.go (hunk 2 above)
Comment (warren830) [reply plugins/helper/worker_scheduler.go:39]: And I tried to let network disconnect until finish all retry, and it works

**Comment by liangjingyang** [comment]
The key point is how to retry a task when error occurred, we shouldn't submit a new task within an uncompleted task recursively. 

There are 2 solutions to achieve this:

1. Let the ApiCollector control the retry, but I think this needs more changes than the second one. It require every handler has a channel to send message from task to ApiCollector, but seems only the handler inside `stepFetch` has a channel currently.
2. Retry by a normal loop inside the task instead of submitting a new task, maybe:
```
var err error
res, err = apiClient.Do(method, path, query, body, header)
for retry < apiClient.maxRetry - 1 && err != nil {
    retry = retry + 1
    res, err = apiClient.Do(method, path, query, body, header)
    ......
}
```

 I think the subpool solution has 2 issues:
1. Introduce a new pool which increases the complexity.
2. The `Sleep` could slow down the data collection when error occurred.

**Comment by hezyin** [comment]
Submitting and waiting for a task within a task is a common cause of deadlocks. One good practice is to only submit tasks from one thread and not expose the pool itself to tasks executed by the pool. I'm leaning towards solution 2 in @liangjingyang's comment.
