### PR TITLE
fix: all plugins apis returning 201

### LINKED ISSUE #704: All plugin apis returning status 201
## Describe the bug
http status code represents `CREATED` which is only suitable for method like `POST` , and yet now all plugin apis returning 201 even for `GET` requests

## To Reproduce
1. Send requests to any jira plugin api
2. All apis returning status code 201

## Expected behavior
Returning 201 if resources created successfully, and 200 for other requests.
image

## Screenshots
image

### PR DESCRIPTION
**Pull request by klesh**
Closes #704

Please check issue for detail

### CODE REVIEW

File: plugins/jira/api/jira_issue_status_mapping.go [hunk 1]
```diff
@@ -135,7 +135,7 @@ func PostIssueStatusMappings(input *core.ApiResourceInput) (*core.ApiResourceOut
 	if err != nil {
 		return nil, err
 	}
-	return &core.ApiResourceOutput{Body: jiraIssueStatusMapping}, nil
+	return &core.ApiResourceOutput{Body: jiraIssueStatusMapping, Status: 201}, nil
```
Comment (narrowizard) [inline plugins/jira/api/jira_issue_status_mapping.go:138]: Why not using `http.StatusCreated` but a constant value `201`? As used above.

Comment (klesh) [reply plugins/jira/api/jira_issue_status_mapping.go:138]: Good point
