### PR TITLE
fix(config-ui): fix duration

### LINKED ISSUE #1618: Config-ui: incorrect pipeline duration
## Describe the bug
Config-ui: incorrect pipeline duration

## To Reproduce
1. Go to config-ui
2. configure a Github connection
3. create a pipeline, toggle on GitHub, and type in the repo to collect
4. After the collection is over, go to the pipeline list. See duration of the pipeline. 
image

## Expected behavior
Should display the actual duration. In this case, the actual duration was about 10min.

### PR DESCRIPTION
**Pull request by warren830**
# Summary

Fix wrong duration in pipeline activity/index
Revert to old warning style, relate to #1609 
### Key Points

- [ ] This is a breaking change
- [ ] New or existing documentation is updated

### Description
Describe what this PR does, and aims to solve in a few sentences.

### Does this close any open issues?
Close #1618 

### Current Behavior
Describe the current behaviour of this issue, if relevant.

### New Behavior
Describe the new behaviour updated in this issue, if relevant.

### Screenshots
image
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: config-ui/src/pages/pipelines/index.jsx [hunk 1]
```diff
@@ -397,7 +397,7 @@ const Pipelines = (props) => {
                             >
 
                               {/* {dayjs(pipeline.CreatedAt).toNow(pipeline.CreatedAt)} */}
-                              {dayjs(pipeline.UpdatedAt).from(pipeline.CreatedAt, true)}
+                              {pipeline.status === 'TASK_RUNNING' ? dayjs(pipeline.beganAt).toNow(pipeline.beganAt) : pipeline.finishedAt == null ? 'N/A' : dayjs(pipeline.finishedAt).from(pipeline.beganAt, true)}
```
Comment (e2corporation) [inline config-ui/src/pages/pipelines/index.jsx:400]: why is `pipeline.beganAt` passed as  arg `toNow()` shouldn't this be empty?
`dayjs(pipeline.beganAt).toNow()`

**Review by e2corporation — APPROVED** [review]
LGTM

**Comment by e2corporation** [comment]
Needs rebase before merging.
