### PR TITLE
fix: system panic when http response code is 503

### LINKED ISSUE #1833: GitLab data collection failed on v0.10.1
## Describe the bug

I tried to collect GitLab data using v0.10.1 but encountered errors. I made two attempts, both with the exact same configuration for the pipeline, but the errors were different (but likely due to the same reason -- rate limit, if I have to guess).

## To Reproduce (first attempt)

1. Use DevLake version v0.10.1
2. Set up our own GitLab instance
3. Try to collect GitLab project 11624398
4. See the following error message at progress 60.87%

Screen Shot 2022-05-09 at 10 42 25 PM

The docker log:

Screen Shot 2022-05-09 at 5 14 39 PM

## To Reproduce (second attempt)

1. Try to collect GitLab project 11624398
2. See the following error message also at progress 60.87%

Screen Shot 2022-05-09 at 10 42 36 PM

The docker log (pretty long so I had to attach 3 screenshots):

Screen Shot 2022-05-09 at 10 45 46 PM
Screen Shot 2022-05-09 at 10 46 02 PM
Screen Shot 2022-05-09 at 10 46 27 PM

### PR DESCRIPTION
**Pull request by mappjzc**
# Summary
Add retry when got the http status code more than 400 even without any error.
also modified corresponding unit test

### Description
In issue #1833 , it failed because it didn't retry when http status code is 503. 
The http request retry only when it has error, to fix, we make sure the http request will retry when the status code  is equal or larger than http.StatusBadRequest(400)

### Does this close any open issues?
closes #1833

### CODE REVIEW

File: plugins/helper/api_async_client.go [hunk 1]
```diff
@@ -121,15 +123,24 @@ func (apiClient *ApiAsyncClient) DoAsync(
 			}
 		}
 
-		// it make sense to retry on request failure, but not error from handler and canceled error
+		// check
+		needRetry := false
 		if err != nil {
+			needRetry = true
+		} else if res.StatusCode >= HttpMinStatusRetryCode {
```
Comment (warren830) [inline plugins/helper/api_async_client.go:130]: can we just use res.StatusCode >=  http.StatusBadRequest?

File: plugins/helper/api_async_client_test.go [hunk 2]
```diff
@@ -289,16 +289,38 @@ func TestDoAsync_TryAndSuceess(t *testing.T) {
 		headers http.Header,
 	) (*http.Response, error) {
 		times++
-		if times <= 3 {
+		switch times {
+		case 1:
 			return &http.Response{
 				Body:       &TestReader{Err: ErrUnitTest},
-				StatusCode: 301,
+				StatusCode: 500,
```
Comment (warren830) [inline plugins/helper/api_async_client_test.go:296]: I think using StatusInternalServerError is more understandable

File: plugins/helper/api_async_client_test.go [hunk 3]
```diff
@@ -289,16 +289,38 @@ func TestDoAsync_TryAndSuceess(t *testing.T) {
...
 			}, nil
-		} else {
+		case 2:
+			return &http.Response{
+				Body:       &TestReader{Err: io.EOF},
+				StatusCode: 500,
```
Comment (warren830) [inline plugins/helper/api_async_client_test.go:301]: same as above

File: plugins/helper/api_async_client_test.go [hunk 4]
```diff
@@ -289,16 +289,38 @@ func TestDoAsync_TryAndSuceess(t *testing.T) {
...
+			}, nil
+		case 3:
+			return &http.Response{
+				Body:       &TestReader{Err: io.EOF},
+				StatusCode: 400,
+			}, nil
```
Comment (warren830) [inline plugins/helper/api_async_client_test.go:307]: I think using StatusBadRequest is more understandable

File: plugins/helper/api_async_client_test.go [hunk 5]
```diff
@@ -289,16 +289,38 @@ func TestDoAsync_TryAndSuceess(t *testing.T) {
...
+		case 4:
+			return &http.Response{
+				Body:       &TestReader{Err: io.EOF},
+				StatusCode: 300,
```
Comment (warren830) [inline plugins/helper/api_async_client_test.go:311]: StatusMultipleChoices

File: plugins/helper/api_async_client_test.go [hunk 6]
```diff
@@ -289,16 +289,38 @@ func TestDoAsync_TryAndSuceess(t *testing.T) {
...
+		case 5:
 			return &http.Response{
 				Body:       &TestReader{Err: io.EOF},
 				StatusCode: 200,
 			}, nil
+		default:
+			assert.Empty(t, TestNoRunHere)
+			return &http.Response{
+				Body:       &TestReader{Err: io.EOF},
+				StatusCode: 200,
```
Comment (warren830) [inline plugins/helper/api_async_client_test.go:322]: StatusOK

**Review by warren830 — APPROVED** [review]
LGTM
