### PR TITLE
fix: enrichment should happen before conversion

### LINKED ISSUE #1019: GitHub issue labels are not extracted and stored in the domain layer table 'issues'
## Describe the bug
GitHub issue labels are not extracted and stored in the domain layer table 'issues' in tag 0.5.0

## To Reproduce
1. Follow the README to install DevLake 0.5.0 by docker-compose
2. Configure the Github endpoint and token
3. Trigger the collection of 'DevLake' project
`[
  [
    {
      "Plugin": "github",
      "Options": {
        "repositoryName": "lake",
        "owner": "merico-dev"
      }
    }
  ]
]`
4. see [requirement lead time](http://localhost:3002/d/SupYz7c7z/demo-how-fast-do-we-respond-to-customer-requirements?orgId=1) chart in demo dashboard

## Expected behavior
The chart displays properly.

## Screenshots
It's empty. No data is retrieved from local MySQL.
image

It seems that issue `type` hasn't been correctly extracted and stored in the domain layer table `issues`
image

### PR DESCRIPTION
**Pull request by klesh**
Closes #1019

### CODE REVIEW

File: plugins/github/github.go [hunk 1]
```diff
@@ -257,7 +257,10 @@ func main() {
 				"owner":          owner,
 				"repositoryName": repo,
 				//"tasks":          []string{"collectCommits"},
-				"tasks": []string{"convertCommits"},
```
Comment (joncodo) [inline plugins/github/github.go:260]: Did you mean to comment this out?

**Review by joncodo — APPROVED** [review]
LGTM
